global using Volo.Abp.BackgroundJobs.EntityFrameworkCore;
global using Volo.Abp.Domain.Repositories.EntityFrameworkCore;
global using Volo.Abp.EntityFrameworkCore;
global using System;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Zemestan.EntityFrameworkCore;
global using Volo.Abp.EntityFrameworkCore.Modeling;
global using System.ComponentModel;
